version: '3.7'

services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    ports:
      - 5001:5001
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    image: 'mongo:latest'
    restart: always
    environment: 
      MONGO_INITDB_DATABASE: crepe_test
    ports:
      - "27016:27017"
    volumes:
      - 'mongodbdata2:/data/db'
  mysql:
    image: mysql
    environment: 
      MYSQL_DATABASE: pl_warehouse
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33211:3306"
    volumes:
      - 'pl_db3:/var/lib/mysql'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--innodb_use_native_aio=0", "--default-authentication-plugin=caching_sha2_password"]
volumes:
  pl_db3:
  mongodbdata2:
